[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mhinz/vim-signify'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_setConceal = 0
'''

[[plugins]]
repo = 'tomasiser/vim-code-dark'
