[[plugins]]
repo = 'andymass/vim-matchup'
hook_add = '''
  let g:matchup_matchparen_offscreen = {'method': 'popup'}
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_do_mapping = 0
  nmap m <Plug>(easymotion-s)
'''

[[plugins]]
repo = 'haya14busa/vim-asterisk'
hook_add = '''
  nmap *  <Plug>(asterisk-z*)
  nmap #  <Plug>(asterisk-z#)
  nmap g* <Plug>(asterisk-gz*)
  nmap g# <Plug>(asterisk-gz#)
  xmap *  <Plug>(asterisk-z*)
  xmap #  <Plug>(asterisk-z#)
  xmap g* <Plug>(asterisk-gz*)
  xmap g# <Plug>(asterisk-gz#)
'''

[[plugins]]
repo = 'kana/vim-smartword'
hook_add = '''
  nmap w  <Plug>(smartword-w)
  nmap b  <Plug>(smartword-b)
  nmap e  <Plug>(smartword-e)
  nmap ge <Plug>(smartword-ge)
  xmap w  <Plug>(smartword-w)
  xmap b  <Plug>(smartword-b)
  xmap e  <Plug>(smartword-e)
  xmap ge <Plug>(smartword-ge)
'''
