execute 'source' fnamemodify($MYVIMRC, ":p:h").'/'.'conf/options.vim'
execute 'source' fnamemodify($MYVIMRC, ":p:h").'/'.'conf/maps.vim'
execute 'source' fnamemodify($MYVIMRC, ":p:h").'/'.'conf/autocmds.vim'
execute 'source' fnamemodify($MYVIMRC, ":p:h").'/'.'conf/functions.vim'
execute 'source' fnamemodify($MYVIMRC, ":p:h").'/'.'conf/plugins/init.vim'

highlight LineNr guifg=grey guibg=black
