hook_add = '''
function! s:go_root_dir()
  let l:gomod = findfile('go.mod', ".;")
  if filereadable(l:gomod)
    return fnamemodify(l:gomod, ':h')
  endif
  return Root_dir()
endfunction
function! s:go_current_func_name()
  let orig_view = winsaveview()
  try
    let l:pattern = '\C'.'^\s*'.'func\>'.'\s\+'.'\((\w\+\s\+[^)]\+)\s\+\)\='.'\('.'[^(]\+'.'\)'.'\%('.'\s*'.'('.'\=\)'
    if search(l:pattern, 'bW') == 0
        return expand("<cword>")
    endif

    let m = matchlist(getline('.'), l:pattern)
    if empty(m)
      return NONE
    endif

    return m[2]
  finally
    call winrestview(orig_view)
  endtry
endfunction
'''

[ftplugin]
go = '''
nnoremap <silent><buffer> [lang]q <Cmd>call Terminal_exec('go run', <SID>go_root_dir())<CR>
nnoremap <silent><buffer> [lang]b <Cmd>call Terminal_exec('go build -v -trimpath -p 4')<CR>
nnoremap <silent><buffer> [lang]s <Cmd>GoAlternate!<CR>
nnoremap <silent><buffer> [lang]t <Cmd>call Terminal_exec('go test ./... -v -parallel 4 -count=1')<CR>
nnoremap <silent><buffer> [lang]f <Cmd>call Terminal_exec('go test -v -run=' . <SID>go_current_func_name())<CR>
nnoremap <silent><buffer> [lang]c <Cmd>GoCoverageToggle<CR>
'''

[[plugins]]
repo = 'buoto/gotests-vim'
on_ft = 'go'
lazy = true
overwrite = true

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_version_warning = 0
  let g:go_code_completion_enabled = 0
  let g:go_def_mapping_enabled = 0
  let g:go_fmt_autosave = 0
  let g:go_imports_autosave = 0
  let g:go_mod_fmt_autosave = 0
  let g:go_metalinter_autosave = 0
  let g:go_textobj_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
  let g:go_gopls_enabled = 0
  let g:go_fold_enable = []
  let g:go_highlight_array_whitespace_error = 0
  let g:go_highlight_chan_whitespace_error = 0
  let g:go_highlight_extra_types = 0
  let g:go_highlight_space_tab_error = 0
  let g:go_highlight_trailing_whitespace_error = 0
  let g:go_highlight_operators = 0
  let g:go_highlight_functions = 0
  let g:go_highlight_function_parameters = 0
  let g:go_highlight_function_calls = 0
  let g:go_highlight_types = 0
  let g:go_highlight_fields = 0
  let g:go_highlight_build_constraints = 0
  let g:go_highlight_generate_tags = 0
  let g:go_highlight_string_spellcheck = 0
  let g:go_highlight_format_strings = 0
  let g:go_highlight_variable_declarations = 0
  let g:go_highlight_variable_assignments = 0
  let g:go_highlight_diagnostic_errors = 0
  let g:go_highlight_diagnostic_warnings = 0

  let g:go_term_mode = "vsplit"
'''
